DUT_IP="172.17.2.70"
FIO_BLOCK_SIZES=("4k" "1m")
FIO_EXTRA_OPTS="randrepeat=0,random_generator=tausworthe64,cpus_allowed_policy=split,norandommap=1"
FIO_IODEPTH=("64")
FIO_MODES=("randread" "read" "randwrite" "write")
FIO_NUMJOBS=("8 max")
FIO_RWMIX=("100")
NVME_INFO="EPW5970-3200GB"
NVME_LIST=("nvme3n1" "nvme4n1" "nvme5n1" "nvme15n1" "nvme14n1" "nvme13n1")
PD_RUNTIME="30"
QD_LS=("64")
QUICK_TEST="true"
RAID_CTRLR="SR-ULTRA-AD"
RAID_TYPE=("RAID5")
REMOTE_MODE="true"
RUN_MD="false"
RUN_PD="true"
RUN_PD_ALL="true"
RUN_VD="true"
STA_LS=("Normal")
TS_LS=("afterdiscard")
USE_BENCH_FIO="true"
VD_NAME="gdg0n1"
VD_RUNTIME="30"
pd_jobs=("8")
