DUT_IP="172.17.2.16"
DUT_PASSWORD="GR@IDt1ch"
FIO_BLOCK_SIZES=("4k" "1m")
FIO_EXTRA_OPTS="randrepeat=0,random_generator=tausworthe64,cpus_allowed_policy=split,norandommap=1"
FIO_IODEPTH=("64")
FIO_MODES=("randread" "read" "randwrite" "write")
FIO_NUMJOBS=("8 max")
FIO_RWMIX=("100")
NVME_INFO="INTEL-SSDPF2KX038TZ"
NVME_LIST=("nvme0n1" "nvme10n1" "nvme11n1" "nvme12n1" "nvme13n1" "nvme14n1" "nvme15n1" "nvme17n1" "nvme18n1" "nvme19n1" "nvme2n1" "nvme4n1" "nvme6n1" "nvme7n1" "nvme9n1")
PD_RUNTIME="60"
QD_LS=("64")
QUICK_TEST="true"
RAID_CTRLR="SR-ULTRA-AD"
RAID_TYPE=("RAID5")
REMOTE_MODE="true"
RUN_MD="false"
RUN_PD="true"
RUN_PD_ALL="true"
RUN_VD="true"
STA_LS=("Normal")
TS_LS=("afterdiscard")
USE_BENCH_FIO="true"
VD_NAME="gdg0n1"
VD_RUNTIME="60"
pd_jobs=("8")
